version: '3.8'

services:
  api:
    build: ./api
    container_name: api
    restart: always
    volumes:
      - './api/:/srv/app'
      - 'static:/srv/app/static'
      - 'media:/srv/app/media'
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgres/data

volumes:
  postgres:
  static:
  media: