version: '3.8'

services:
  api:
    build: ./api
    container_name: api
    volumes:
      - './api/:/srv/app'
      - 'static:/srv/app/static'
      - 'media:/srv/app/media'
    env_file:
      - ./.env.dev
  redis:
    image: redis:6.2.6-alpine
    container_name: redis
    env_file:
      - ./.env.dev
    ports:
      - 6379:6379
    volumes:
      - redis:/var/lib/redis/data